"""empty message

Revision ID: 60e02fc5b93a
Revises: 44b7b61c427d
Create Date: 2023-02-18 20:24:16.250448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e02fc5b93a'
down_revision = '44b7b61c427d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amort_period', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('amort_period')

    # ### end Alembic commands ###
